### ISSUE TITLE
The Gollum --base-path option

### ISSUE THREAD

**Issue by njman** [intridea/omniauth-ldap#54]
I want wiki sub-directory, e.g. `http://localhost:4567/wiki/Home`, `/wiki/` is the sub-directory.

[Gollum][1] support --base-path option in Rack way, please check the [wiki tips][2].
The [omnigollum][3] support it by [the pull][4].
However, `omniauth-ldap` has `Sign In` problem, i.e. always return to Home page once submit.
Look around the `LDAP Authentication` html source:

```html
      <body>
      <h1>LDAP Authentication</h1>
      <form method='post' action='/__omnigollum__/auth/ldap/callback' noValidate='noValidate'>

<label for='username'>Login:</label>
<input type='text' id='username' name='username'/>
<label for='password'>Password:</label>
<input type='password' id='password' name='password'/>
<button type='submit'>Sign In</button>      </form>
      </body>
```

I doubted on this line: 
  
`action='/__omnigollum__/auth/ldap/callback' `

should write:

`action='/wiki/__omnigollum__/auth/ldap/callback' `

Not sure. How to resolve this problem, thanks.

[1]: https://github.com/gollum/gollum
[2]: https://github.com/gollum/gollum/wiki/Using-Gollum-with-Rack
[3]: https://github.com/arr2036/omnigollum/
[4]: https://github.com/arr2036/omnigollum/pull/30

**Comment by aldanor** [comment]
I fixed it for myself by doing something like this:

```ruby
module OmniAuthLDAPExt
    require 'omniauth'

    def request_phase
        @callback_path = nil
        path = options[:callback_path]
        options[:callback_path] = callback_url
        form = super
        options[:callback_path] = path
        form
    end
end

module OmniAuth
    module Strategies
        class LDAP
            prepend OmniAuthLDAPExt
        end
    end
end
```

**Comment by aldanor** [comment]
Maybe this should be just fixed in master...

**Comment by njman** [comment]
@aldanor Could you provide the fork patch? I don't know how to handle the fix above you mentioned. Thanks.

**Comment by njman** [comment]
@aldanor Could you provide the fork patch? I don't know how to handle the fix above you mentioned. Thanks.

**Comment by njman** [comment]
With your patch, it worked. Thank you, @aldanor .

**Comment by aldanor** [comment]
@njman np.

@pyu10055 Do you think it makes sense to merge it in master?
